### ISSUE TITLE
Error when running test_executor_humaneval

### ISSUE THREAD

**Issue by HamedTaherkhani** [huangd1999/AgentCoder#1]
Hi,
I am getting this error:

`Traceback (most recent call last):
  File "AgentCoder/test_executor_humaneval.py", line 323, in <module>
    test_report(dataset,lg)
  File "AgentCoder/test_executor_humaneval.py", line 290, in test_report
    result = check_correctness(dataset[i]["task_id"],dataset[i],lg,5,"./tmp")
  File "AgentCoder/./CodeGeeX/codegeex/benchmark/execution.py", line 378, in check_correctness
    "test_code"    : sample["test_code"],
KeyError: 'test_code'`

Can you please fix this?

**Comment by huangd1999** [comment]
Hi, I have checked the source code provided by CodeGeeX. I think this problem can be addressed by directly replacing "test_code" with "full_code".

By the way, we have updated human eval files since we observed that the results will be hard to control with massive prompt instruction. In the current version, the pass@1 of humaneval for ChatGPT increases from 79.9% to 80.5%. You can pull the repo for the new version.

**Comment by DorothyDUUU** [comment]
This key is not defined in the AgentCoder code, so I change the code in the part CodeGeeX.

**Comment by huangd1999** [comment]
Hi, the generation may be a key for CodeGeeX's original input dictionary. We remove this part from our version. 

To address these errors, we can remove the original part in ./CodeGeeX/codegeex/benchmark/execution.py Line 337 with the below return dictionary. 

```
    return {
        "task_id"      : task_id,
        "completion_id": completion_id,
        "full_code"    : sample["full_code"],
        "prompt"       : sample["prompt"],
        "completion"   : sample["completion"],
        "result"       : result[0],
        "passed"       : result[0] == "passed",
        "finish"       : -1 if "finish" not in sample else sample["finish"],
        "file"         : "" if "file" not in sample else sample["file"],
        "output"       : [] if "output" not in sample else sample["output"],
    }
```

**Comment by DorothyDUUU** [comment]
Thanks for your response. That's exactly what I did. Just to check if that is valid. :)

**Comment by LainWiredIn** [comment]
Even after replacing the return block with the one mentioned here, it is unable to find "completion". I still seem to be getting KeyError: 'completion'

**Comment by huangd1999** [comment]
Hi, 'completion' is generated with programmer_[humaneval/mbpp].py
You can check the source code in https://github.com/huangd1999/AgentCoder/blob/cdfce4ab074a09b0433fa95d980d0fcf11c4ccbe/programmer_humaneval.py

**Comment by LainWiredIn** [comment]
Is completion the same as completion_list? Because it is completion_list that is generated by programmer_humaneval.py.

________________________________

**Comment by huangd1999** [comment]
Completion is sampled from completion_lists, where completion_lists currently generate five different source codes.

**Comment by LainWiredIn** [comment]
Thank you for your prompt responses. I really do appreciate them.

Shouldn't "def process_item(i)" (line 194 in test_executor_humaneval.py) be after the block of code from 221 to 235?

Completion is sampled at line 228 but it's presence is checked at line 221 (result = check_correctness(dataset[i]["task_id"], dataset[i], lg, 3, "./tmp")) when check_correctness from codegeex is called.

The code doesn't process anything beyond the line 221 for me. I keep getting a key error for "completion".

Please correct me if I am wrong.

Thank you once again!

**Comment by LainWiredIn** [comment]
I’ve been working on reproducing your work from the AgentCoder repository, but I’m running into a KeyError because the "completion" field does not exist at the point when check_correctness is called.

```
futures = [executor.submit(process_item, i) for i in range(len(dataset))]

        for future in tqdm(concurrent.futures.as_completed(futures), total=len(dataset)):
            max_correct, idx = future.result()
            if max_correct >= 3: # GPT-3.5-turbo-1106's test case accuracy is about 67%. So we choice 60% as the bar.
                i = futures.index(future)
                dataset[i]["completion"] = dataset[i]["completion_list"][idx]
```

It seems that the sampling of "completion_lists" occurs after process_item is called, where `check_correctness` is executed. According to the code in codegeex/benchmark/execution.py, `check_correctness` is supposed to return the following:
```
return {
        "task_id"      : task_id,
        "completion_id": completion_id,
        "full_code"    : sample["full_code"],
        "prompt"       : sample["prompt"],
        "completion"   : sample["completion"],
        "result"       : result[0],
        "passed"       : result[0] == "passed",
        "finish"       : -1 if "finish" not in sample else sample["finish"],
        "file"         : "" if "file" not in sample else sample["file"],
        "output"       : [] if "output" not in sample else sample["output"],
    }
```
That's when the key error happens. Could you please advise if there are any alternate versions of the code that handle this correctly? It seems that the sampling of "completion_lists" needs to happen before check_correctness is called to avoid this error.

Thank you for your time, and I appreciate any guidance you can provide.

**Comment by huangd1999** [comment]
Hi，
I think you can directly use the version (https://github.com/huangd1999/AgentCoder/issues/1#issuecomment-2313948409) provided at https://github.com/huangd1999/AgentCoder/blob/cdfce4ab074a09b0433fa95d980d0fcf11c4ccbe/programmer_humaneval.py

While current source code is under development for multiple executions.

**Comment by imabs7** [comment]
i am facing issue in installing req.txt 
deepespeed is not getting installed

please help

**Comment by imabs7** [comment]
what to do with the two .py file where to create it and what to write in this

**Comment by huangd1999** [comment]
Hi, deepspeed can be directly installed by `pip install deepspeed`

**Comment by huangd1999** [comment]
In addition, I will push our newest AgentCoder this week, while the paper will be rewritten in two to three weeks.

**Comment by imabs7** [comment]
i tried the smae pip install deepspeed but it is giving error "AssertionError: Unable to pre-compile async_io
      [WARNING] Torch did not find cuda available, if cross-compiling or running with cpu only you can ignore this message. Adding compute capability for Pascal, Volta, and Turing (compute capabilities 6.0, 6.1, 6.2)"
      
but i have installed torch

another problem is that when i am installing any particular version "numpy>=1.22.0" but it installed latest version (2.1.2) by default for each library in requirements.txt

**Comment by huangd1999** [comment]
Hi， can you provide the results of nvidia-smi and conda list? Seems like you are install torch-cpu?

**Comment by imabs7** [comment]
yes i have installed cpu version of torch
